// ============================================
// CollegeTrue - School & Major Data
// Sources: College Scorecard, BLS OES, IPEDS
// 500+ US colleges with financial data
// ============================================

const SCHOOLS = {
  // ---- Ivy League ----
  "harvard":           { name:"Harvard",            fullName:"Harvard University",                 tuition:59076, type:"Private Non-Profit", state:"MA", city:"Cambridge",      domain:"harvard.edu" },
  "yale":              { name:"Yale",                fullName:"Yale University",                    tuition:62250, type:"Private Non-Profit", state:"CT", city:"New Haven",       domain:"yale.edu" },
  "princeton":         { name:"Princeton",           fullName:"Princeton University",               tuition:57410, type:"Private Non-Profit", state:"NJ", city:"Princeton",       domain:"princeton.edu" },
  "columbia":          { name:"Columbia",            fullName:"Columbia University",                tuition:65524, type:"Private Non-Profit", state:"NY", city:"New York City",   domain:"columbia.edu" },
  "upenn":             { name:"UPenn",               fullName:"University of Pennsylvania",         tuition:63452, type:"Private Non-Profit", state:"PA", city:"Philadelphia",    domain:"upenn.edu" },
  "university of pennsylvania": { name:"UPenn",      fullName:"University of Pennsylvania",         tuition:63452, type:"Private Non-Profit", state:"PA", city:"Philadelphia",    domain:"upenn.edu" },
  "dartmouth":         { name:"Dartmouth",           fullName:"Dartmouth College",                  tuition:61947, type:"Private Non-Profit", state:"NH", city:"Hanover",         domain:"dartmouth.edu" },
  "brown":             { name:"Brown",               fullName:"Brown University",                   tuition:65146, type:"Private Non-Profit", state:"RI", city:"Providence",       domain:"brown.edu" },
  "cornell":           { name:"Cornell",             fullName:"Cornell University",                 tuition:63200, type:"Private Non-Profit", state:"NY", city:"Ithaca",          domain:"cornell.edu" },

  // ---- Other Elite Privates ----
  "mit":               { name:"MIT",                 fullName:"Massachusetts Institute of Technology", tuition:57986, type:"Private Non-Profit", state:"MA", city:"Cambridge",   domain:"mit.edu" },
  "stanford":          { name:"Stanford",            fullName:"Stanford University",                tuition:62484, type:"Private Non-Profit", state:"CA", city:"Stanford",        domain:"stanford.edu" },
  "caltech":           { name:"Caltech",             fullName:"California Institute of Technology", tuition:60816, type:"Private Non-Profit", state:"CA", city:"Pasadena",        domain:"caltech.edu" },
  "duke":              { name:"Duke",                fullName:"Duke University",                    tuition:62688, type:"Private Non-Profit", state:"NC", city:"Durham",          domain:"duke.edu" },
  "northwestern":      { name:"Northwestern",        fullName:"Northwestern University",            tuition:63468, type:"Private Non-Profit", state:"IL", city:"Evanston",        domain:"northwestern.edu" },
  "vanderbilt":        { name:"Vanderbilt",          fullName:"Vanderbilt University",              tuition:59448, type:"Private Non-Profit", state:"TN", city:"Nashville",       domain:"vanderbilt.edu" },
  "uchicago":          { name:"UChicago",            fullName:"University of Chicago",              tuition:64260, type:"Private Non-Profit", state:"IL", city:"Chicago",         domain:"uchicago.edu" },
  "university of chicago": { name:"UChicago",        fullName:"University of Chicago",              tuition:64260, type:"Private Non-Profit", state:"IL", city:"Chicago",         domain:"uchicago.edu" },
  "notre dame":        { name:"Notre Dame",          fullName:"University of Notre Dame",           tuition:60301, type:"Private Non-Profit", state:"IN", city:"Notre Dame",      domain:"nd.edu" },
  "johns hopkins":     { name:"Johns Hopkins",       fullName:"Johns Hopkins University",           tuition:60480, type:"Private Non-Profit", state:"MD", city:"Baltimore",       domain:"jhu.edu" },
  "tufts":             { name:"Tufts",               fullName:"Tufts University",                   tuition:63804, type:"Private Non-Profit", state:"MA", city:"Medford",         domain:"tufts.edu" },
  "carnegie mellon":   { name:"Carnegie Mellon",     fullName:"Carnegie Mellon University",         tuition:61344, type:"Private Non-Profit", state:"PA", city:"Pittsburgh",      domain:"cmu.edu" },
  "emory":             { name:"Emory",               fullName:"Emory University",                   tuition:57948, type:"Private Non-Profit", state:"GA", city:"Atlanta",         domain:"emory.edu" },
  "rice":              { name:"Rice",                fullName:"Rice University",                    tuition:54960, type:"Private Non-Profit", state:"TX", city:"Houston",         domain:"rice.edu" },
  "wake forest":       { name:"Wake Forest",         fullName:"Wake Forest University",             tuition:62568, type:"Private Non-Profit", state:"NC", city:"Winston-Salem",   domain:"wfu.edu" },
  "georgetown":        { name:"Georgetown",          fullName:"Georgetown University",              tuition:62868, type:"Private Non-Profit", state:"DC", city:"Washington",      domain:"georgetown.edu" },
  "nyu":               { name:"NYU",                 fullName:"New York University",                tuition:58168, type:"Private Non-Profit", state:"NY", city:"New York City",   domain:"nyu.edu" },
  "new york university": { name:"NYU",               fullName:"New York University",                tuition:58168, type:"Private Non-Profit", state:"NY", city:"New York City",   domain:"nyu.edu" },
  "boston university": { name:"Boston University",   fullName:"Boston University",                  tuition:63534, type:"Private Non-Profit", state:"MA", city:"Boston",          domain:"bu.edu" },
  "boston college":    { name:"Boston College",      fullName:"Boston College",                     tuition:62950, type:"Private Non-Profit", state:"MA", city:"Chestnut Hill",   domain:"bc.edu" },
  "tulane":            { name:"Tulane",              fullName:"Tulane University",                  tuition:60696, type:"Private Non-Profit", state:"LA", city:"New Orleans",     domain:"tulane.edu" },
  "lehigh":            { name:"Lehigh",              fullName:"Lehigh University",                  tuition:59980, type:"Private Non-Profit", state:"PA", city:"Bethlehem",       domain:"lehigh.edu" },
  "fordham":           { name:"Fordham",             fullName:"Fordham University",                 tuition:57986, type:"Private Non-Profit", state:"NY", city:"New York City",   domain:"fordham.edu" },
  "villanova":         { name:"Villanova",           fullName:"Villanova University",               tuition:59685, type:"Private Non-Profit", state:"PA", city:"Villanova",       domain:"villanova.edu" },
  "rochester":         { name:"Rochester",           fullName:"University of Rochester",            tuition:62280, type:"Private Non-Profit", state:"NY", city:"Rochester",       domain:"rochester.edu" },
  "case western":      { name:"Case Western",        fullName:"Case Western Reserve University",    tuition:58572, type:"Private Non-Profit", state:"OH", city:"Cleveland",       domain:"case.edu" },
  "american university": { name:"American University", fullName:"American University",             tuition:51888, type:"Private Non-Profit", state:"DC", city:"Washington",      domain:"american.edu" },
  "brandeis":          { name:"Brandeis",            fullName:"Brandeis University",                tuition:61490, type:"Private Non-Profit", state:"MA", city:"Waltham",         domain:"brandeis.edu" },
  "rpi":               { name:"RPI",                 fullName:"Rensselaer Polytechnic Institute",   tuition:60294, type:"Private Non-Profit", state:"NY", city:"Troy",            domain:"rpi.edu" },
  "rensselaer":        { name:"RPI",                 fullName:"Rensselaer Polytechnic Institute",   tuition:60294, type:"Private Non-Profit", state:"NY", city:"Troy",            domain:"rpi.edu" },
  "northeastern":      { name:"Northeastern",        fullName:"Northeastern University",            tuition:57528, type:"Private Non-Profit", state:"MA", city:"Boston",          domain:"northeastern.edu" },
  "drexel":            { name:"Drexel",              fullName:"Drexel University",                  tuition:56895, type:"Private Non-Profit", state:"PA", city:"Philadelphia",    domain:"drexel.edu" },
  "george washington": { name:"George Washington",   fullName:"George Washington University",       tuition:60856, type:"Private Non-Profit", state:"DC", city:"Washington",      domain:"gwu.edu" },
  "usc":               { name:"USC",                 fullName:"University of Southern California",  tuition:64726, type:"Private Non-Profit", state:"CA", city:"Los Angeles",     domain:"usc.edu" },
  "university of southern california": { name:"USC", fullName:"University of Southern California",  tuition:64726, type:"Private Non-Profit", state:"CA", city:"Los Angeles",     domain:"usc.edu" },

  // ---- Flagship Public Universities ----
  "ohio state":        { name:"Ohio State",          fullName:"Ohio State University",              tuition:11518, type:"Public", state:"OH", city:"Columbus",          domain:"osu.edu" },
  "michigan":          { name:"Michigan",            fullName:"University of Michigan",             tuition:16564, type:"Public", state:"MI", city:"Ann Arbor",         domain:"umich.edu" },
  "university of michigan": { name:"Michigan",       fullName:"University of Michigan",             tuition:16564, type:"Public", state:"MI", city:"Ann Arbor",         domain:"umich.edu" },
  "unc":               { name:"UNC",                 fullName:"UNC Chapel Hill",                    tuition: 9005, type:"Public", state:"NC", city:"Chapel Hill",       domain:"unc.edu" },
  "unc chapel hill":   { name:"UNC Chapel Hill",     fullName:"UNC Chapel Hill",                    tuition: 9005, type:"Public", state:"NC", city:"Chapel Hill",       domain:"unc.edu" },
  "virginia":          { name:"Virginia",            fullName:"University of Virginia",             tuition:17978, type:"Public", state:"VA", city:"Charlottesville",   domain:"virginia.edu" },
  "university of virginia": { name:"Virginia",       fullName:"University of Virginia",             tuition:17978, type:"Public", state:"VA", city:"Charlottesville",   domain:"virginia.edu" },
  "uva":               { name:"UVA",                 fullName:"University of Virginia",             tuition:17978, type:"Public", state:"VA", city:"Charlottesville",   domain:"virginia.edu" },
  "georgia tech":      { name:"Georgia Tech",        fullName:"Georgia Institute of Technology",    tuition:11764, type:"Public", state:"GA", city:"Atlanta",           domain:"gatech.edu" },
  "georgia institute": { name:"Georgia Tech",        fullName:"Georgia Institute of Technology",    tuition:11764, type:"Public", state:"GA", city:"Atlanta",           domain:"gatech.edu" },
  "florida":           { name:"Florida",             fullName:"University of Florida",              tuition: 6381, type:"Public", state:"FL", city:"Gainesville",       domain:"ufl.edu" },
  "university of florida": { name:"Florida",         fullName:"University of Florida",              tuition: 6381, type:"Public", state:"FL", city:"Gainesville",       domain:"ufl.edu" },
  "uf":                { name:"UF",                  fullName:"University of Florida",              tuition: 6381, type:"Public", state:"FL", city:"Gainesville",       domain:"ufl.edu" },
  "texas":             { name:"UT Austin",           fullName:"University of Texas at Austin",      tuition:11448, type:"Public", state:"TX", city:"Austin",            domain:"utexas.edu" },
  "ut austin":         { name:"UT Austin",           fullName:"University of Texas at Austin",      tuition:11448, type:"Public", state:"TX", city:"Austin",            domain:"utexas.edu" },
  "university of texas": { name:"UT Austin",         fullName:"University of Texas at Austin",      tuition:11448, type:"Public", state:"TX", city:"Austin",            domain:"utexas.edu" },
  "arizona state":     { name:"Arizona State",       fullName:"Arizona State University",           tuition:11788, type:"Public", state:"AZ", city:"Tempe",             domain:"asu.edu" },
  "asu":               { name:"ASU",                 fullName:"Arizona State University",           tuition:11788, type:"Public", state:"AZ", city:"Tempe",             domain:"asu.edu" },
  "purdue":            { name:"Purdue",              fullName:"Purdue University",                  tuition: 9992, type:"Public", state:"IN", city:"West Lafayette",    domain:"purdue.edu" },
  "penn state":        { name:"Penn State",          fullName:"Penn State University",              tuition:18454, type:"Public", state:"PA", city:"State College",     domain:"psu.edu" },
  "illinois":          { name:"Illinois",            fullName:"University of Illinois Urbana-Champaign", tuition:16862, type:"Public", state:"IL", city:"Champaign",   domain:"illinois.edu" },
  "uiuc":              { name:"UIUC",                fullName:"University of Illinois Urbana-Champaign", tuition:16862, type:"Public", state:"IL", city:"Champaign",   domain:"illinois.edu" },
  "minnesota":         { name:"Minnesota",           fullName:"University of Minnesota",            tuition:15312, type:"Public", state:"MN", city:"Minneapolis",       domain:"umn.edu" },
  "university of minnesota": { name:"Minnesota",     fullName:"University of Minnesota",            tuition:15312, type:"Public", state:"MN", city:"Minneapolis",       domain:"umn.edu" },
  "maryland":          { name:"Maryland",            fullName:"University of Maryland",             tuition:10595, type:"Public", state:"MD", city:"College Park",      domain:"umd.edu" },
  "umd":               { name:"UMD",                 fullName:"University of Maryland",             tuition:10595, type:"Public", state:"MD", city:"College Park",      domain:"umd.edu" },
  "rutgers":           { name:"Rutgers",             fullName:"Rutgers University",                 tuition:15507, type:"Public", state:"NJ", city:"New Brunswick",     domain:"rutgers.edu" },
  "colorado":          { name:"Colorado",            fullName:"University of Colorado Boulder",     tuition:12904, type:"Public", state:"CO", city:"Boulder",           domain:"colorado.edu" },
  "cu boulder":        { name:"CU Boulder",          fullName:"University of Colorado Boulder",     tuition:12904, type:"Public", state:"CO", city:"Boulder",           domain:"colorado.edu" },
  "iowa":              { name:"Iowa",                fullName:"University of Iowa",                 tuition: 9809, type:"Public", state:"IA", city:"Iowa City",         domain:"uiowa.edu" },
  "university of iowa": { name:"Iowa",               fullName:"University of Iowa",                 tuition: 9809, type:"Public", state:"IA", city:"Iowa City",         domain:"uiowa.edu" },
  "iowa state":        { name:"Iowa State",          fullName:"Iowa State University",              tuition: 9010, type:"Public", state:"IA", city:"Ames",              domain:"iastate.edu" },
  "indiana":           { name:"Indiana",             fullName:"Indiana University Bloomington",     tuition:10533, type:"Public", state:"IN", city:"Bloomington",       domain:"iu.edu" },
  "iu":                { name:"IU",                  fullName:"Indiana University Bloomington",     tuition:10533, type:"Public", state:"IN", city:"Bloomington",       domain:"iu.edu" },
  "michigan state":    { name:"Michigan State",      fullName:"Michigan State University",          tuition:14460, type:"Public", state:"MI", city:"East Lansing",      domain:"msu.edu" },
  "msu":               { name:"MSU",                 fullName:"Michigan State University",          tuition:14460, type:"Public", state:"MI", city:"East Lansing",      domain:"msu.edu" },
  "ohio":              { name:"Ohio University",     fullName:"Ohio University",                    tuition:12192, type:"Public", state:"OH", city:"Athens",            domain:"ohio.edu" },
  "pittsburgh":        { name:"Pittsburgh",          fullName:"University of Pittsburgh",           tuition:20422, type:"Public", state:"PA", city:"Pittsburgh",        domain:"pitt.edu" },
  "pitt":              { name:"Pitt",                fullName:"University of Pittsburgh",           tuition:20422, type:"Public", state:"PA", city:"Pittsburgh",        domain:"pitt.edu" },
  "kentucky":          { name:"Kentucky",            fullName:"University of Kentucky",             tuition:12578, type:"Public", state:"KY", city:"Lexington",         domain:"uky.edu" },
  "tennessee":         { name:"Tennessee",           fullName:"University of Tennessee",            tuition:13244, type:"Public", state:"TN", city:"Knoxville",         domain:"utk.edu" },
  "georgia":           { name:"Georgia",             fullName:"University of Georgia",              tuition:11180, type:"Public", state:"GA", city:"Athens",            domain:"uga.edu" },
  "uga":               { name:"UGA",                 fullName:"University of Georgia",              tuition:11180, type:"Public", state:"GA", city:"Athens",            domain:"uga.edu" },
  "auburn":            { name:"Auburn",              fullName:"Auburn University",                  tuition:11826, type:"Public", state:"AL", city:"Auburn",            domain:"auburn.edu" },
  "alabama":           { name:"Alabama",             fullName:"University of Alabama",              tuition:11100, type:"Public", state:"AL", city:"Tuscaloosa",        domain:"ua.edu" },
  "south carolina":    { name:"South Carolina",      fullName:"University of South Carolina",       tuition:13518, type:"Public", state:"SC", city:"Columbia",          domain:"sc.edu" },
  "clemson":           { name:"Clemson",             fullName:"Clemson University",                 tuition:15116, type:"Public", state:"SC", city:"Clemson",           domain:"clemson.edu" },
  "florida state":     { name:"Florida State",       fullName:"Florida State University",           tuition: 5656, type:"Public", state:"FL", city:"Tallahassee",       domain:"fsu.edu" },
  "fsu":               { name:"FSU",                 fullName:"Florida State University",           tuition: 5656, type:"Public", state:"FL", city:"Tallahassee",       domain:"fsu.edu" },
  "miami":             { name:"Miami",               fullName:"University of Miami",                tuition:56848, type:"Private Non-Profit", state:"FL", city:"Coral Gables",  domain:"miami.edu" },
  "university of miami": { name:"Miami",             fullName:"University of Miami",                tuition:56848, type:"Private Non-Profit", state:"FL", city:"Coral Gables",  domain:"miami.edu" },
  "washington":        { name:"UW",                  fullName:"University of Washington",           tuition:12076, type:"Public", state:"WA", city:"Seattle",           domain:"uw.edu" },
  "university of washington": { name:"UW",           fullName:"University of Washington",           tuition:12076, type:"Public", state:"WA", city:"Seattle",           domain:"uw.edu" },
  "uw":                { name:"UW",                  fullName:"University of Washington",           tuition:12076, type:"Public", state:"WA", city:"Seattle",           domain:"uw.edu" },
  "oregon":            { name:"Oregon",              fullName:"University of Oregon",               tuition:13407, type:"Public", state:"OR", city:"Eugene",            domain:"uoregon.edu" },
  "oregon state":      { name:"Oregon State",        fullName:"Oregon State University",            tuition:12138, type:"Public", state:"OR", city:"Corvallis",         domain:"oregonstate.edu" },
  "utah":              { name:"Utah",                fullName:"University of Utah",                 tuition: 9228, type:"Public", state:"UT", city:"Salt Lake City",    domain:"utah.edu" },
  "nebraska":          { name:"Nebraska",            fullName:"University of Nebraska-Lincoln",     tuition: 9432, type:"Public", state:"NE", city:"Lincoln",           domain:"unl.edu" },
  "kansas":            { name:"Kansas",              fullName:"University of Kansas",               tuition:11166, type:"Public", state:"KS", city:"Lawrence",          domain:"ku.edu" },
  "kansas state":      { name:"Kansas State",        fullName:"Kansas State University",            tuition:10002, type:"Public", state:"KS", city:"Manhattan",         domain:"ksu.edu" },
  "missouri":          { name:"Missouri",            fullName:"University of Missouri",             tuition:10568, type:"Public", state:"MO", city:"Columbia",          domain:"missouri.edu" },
  "mizzou":            { name:"Mizzou",              fullName:"University of Missouri",             tuition:10568, type:"Public", state:"MO", city:"Columbia",          domain:"missouri.edu" },
  "arkansas":          { name:"Arkansas",            fullName:"University of Arkansas",             tuition: 9326, type:"Public", state:"AR", city:"Fayetteville",      domain:"uark.edu" },
  "mississippi":       { name:"Ole Miss",            fullName:"University of Mississippi",          tuition: 9028, type:"Public", state:"MS", city:"Oxford",            domain:"olemiss.edu" },
  "ole miss":          { name:"Ole Miss",            fullName:"University of Mississippi",          tuition: 9028, type:"Public", state:"MS", city:"Oxford",            domain:"olemiss.edu" },
  "mississippi state": { name:"Mississippi State",   fullName:"Mississippi State University",       tuition: 9042, type:"Public", state:"MS", city:"Starkville",        domain:"msstate.edu" },
  "lsu":               { name:"LSU",                 fullName:"Louisiana State University",         tuition: 8038, type:"Public", state:"LA", city:"Baton Rouge",       domain:"lsu.edu" },
  "oklahoma":          { name:"Oklahoma",            fullName:"University of Oklahoma",             tuition: 9394, type:"Public", state:"OK", city:"Norman",            domain:"ou.edu" },
  "oklahoma state":    { name:"Oklahoma State",      fullName:"Oklahoma State University",          tuition: 8798, type:"Public", state:"OK", city:"Stillwater",        domain:"okstate.edu" },
  "colorado state":    { name:"Colorado State",      fullName:"Colorado State University",          tuition:12384, type:"Public", state:"CO", city:"Fort Collins",      domain:"colostate.edu" },
  "new mexico":        { name:"New Mexico",          fullName:"University of New Mexico",           tuition: 7740, type:"Public", state:"NM", city:"Albuquerque",       domain:"unm.edu" },
  "nevada":            { name:"Nevada",              fullName:"University of Nevada Reno",          tuition: 7844, type:"Public", state:"NV", city:"Reno",              domain:"unr.edu" },
  "unlv":              { name:"UNLV",                fullName:"University of Nevada Las Vegas",     tuition: 8376, type:"Public", state:"NV", city:"Las Vegas",         domain:"unlv.edu" },
  "idaho":             { name:"Idaho",               fullName:"University of Idaho",                tuition: 7658, type:"Public", state:"ID", city:"Moscow",            domain:"uidaho.edu" },
  "montana":           { name:"Montana",             fullName:"University of Montana",              tuition: 7234, type:"Public", state:"MT", city:"Missoula",          domain:"umt.edu" },
  "wyoming":           { name:"Wyoming",             fullName:"University of Wyoming",              tuition: 5772, type:"Public", state:"WY", city:"Laramie",           domain:"uwyo.edu" },
  "north dakota":      { name:"North Dakota",        fullName:"University of North Dakota",         tuition: 9006, type:"Public", state:"ND", city:"Grand Forks",       domain:"und.edu" },
  "south dakota":      { name:"South Dakota",        fullName:"University of South Dakota",         tuition: 9332, type:"Public", state:"SD", city:"Vermillion",        domain:"usd.edu" },
  "west virginia":     { name:"West Virginia",       fullName:"West Virginia University",           tuition: 9360, state:"WV", city:"Morgantown", type:"Public",         domain:"wvu.edu" },
  "delaware":          { name:"Delaware",            fullName:"University of Delaware",             tuition:14520, type:"Public", state:"DE", city:"Newark",            domain:"udel.edu" },
  "connecticut":       { name:"UConn",               fullName:"University of Connecticut",          tuition:18084, type:"Public", state:"CT", city:"Storrs",            domain:"uconn.edu" },
  "uconn":             { name:"UConn",               fullName:"University of Connecticut",          tuition:18084, type:"Public", state:"CT", city:"Storrs",            domain:"uconn.edu" },
  "rhode island":      { name:"Rhode Island",        fullName:"University of Rhode Island",         tuition:15132, type:"Public", state:"RI", city:"Kingston",          domain:"uri.edu" },
  "new hampshire":     { name:"New Hampshire",       fullName:"University of New Hampshire",        tuition:18499, type:"Public", state:"NH", city:"Durham",            domain:"unh.edu" },
  "maine":             { name:"Maine",               fullName:"University of Maine",                tuition:11472, type:"Public", state:"ME", city:"Orono",             domain:"umaine.edu" },
  "vermont":           { name:"Vermont",             fullName:"University of Vermont",              tuition:17280, type:"Public", state:"VT", city:"Burlington",        domain:"uvm.edu" },
  "hawaii":            { name:"Hawaii",              fullName:"University of Hawaii at Manoa",      tuition:11304, type:"Public", state:"HI", city:"Honolulu",          domain:"hawaii.edu" },
  "alaska":            { name:"Alaska",              fullName:"University of Alaska Fairbanks",     tuition: 7920, type:"Public", state:"AK", city:"Fairbanks",         domain:"uaf.edu" },

  // ---- California UC System ----
  "ucla":              { name:"UCLA",                fullName:"University of California Los Angeles", tuition:13249, type:"Public", state:"CA", city:"Los Angeles",     domain:"ucla.edu" },
  "uc berkeley":       { name:"UC Berkeley",         fullName:"University of California Berkeley",  tuition:14312, type:"Public", state:"CA", city:"Berkeley",          domain:"berkeley.edu" },
  "berkeley":          { name:"UC Berkeley",         fullName:"University of California Berkeley",  tuition:14312, type:"Public", state:"CA", city:"Berkeley",          domain:"berkeley.edu" },
  "ucsd":              { name:"UCSD",                fullName:"UC San Diego",                       tuition:14490, type:"Public", state:"CA", city:"San Diego",         domain:"ucsd.edu" },
  "uc san diego":      { name:"UCSD",                fullName:"UC San Diego",                       tuition:14490, type:"Public", state:"CA", city:"San Diego",         domain:"ucsd.edu" },
  "uci":               { name:"UCI",                 fullName:"UC Irvine",                          tuition:13752, type:"Public", state:"CA", city:"Irvine",            domain:"uci.edu" },
  "uc irvine":         { name:"UCI",                 fullName:"UC Irvine",                          tuition:13752, type:"Public", state:"CA", city:"Irvine",            domain:"uci.edu" },
  "ucsb":              { name:"UCSB",                fullName:"UC Santa Barbara",                   tuition:14312, type:"Public", state:"CA", city:"Santa Barbara",     domain:"ucsb.edu" },
  "uc santa barbara":  { name:"UCSB",                fullName:"UC Santa Barbara",                   tuition:14312, type:"Public", state:"CA", city:"Santa Barbara",     domain:"ucsb.edu" },
  "ucd":               { name:"UC Davis",            fullName:"UC Davis",                           tuition:14489, type:"Public", state:"CA", city:"Davis",             domain:"ucdavis.edu" },
  "uc davis":          { name:"UC Davis",            fullName:"UC Davis",                           tuition:14489, type:"Public", state:"CA", city:"Davis",             domain:"ucdavis.edu" },
  "ucr":               { name:"UCR",                 fullName:"UC Riverside",                       tuition:13994, type:"Public", state:"CA", city:"Riverside",         domain:"ucr.edu" },
  "uc riverside":      { name:"UCR",                 fullName:"UC Riverside",                       tuition:13994, type:"Public", state:"CA", city:"Riverside",         domain:"ucr.edu" },
  "ucsc":              { name:"UCSC",                fullName:"UC Santa Cruz",                      tuition:14312, type:"Public", state:"CA", city:"Santa Cruz",        domain:"ucsc.edu" },
  "uc santa cruz":     { name:"UCSC",                fullName:"UC Santa Cruz",                      tuition:14312, type:"Public", state:"CA", city:"Santa Cruz",        domain:"ucsc.edu" },

  // ---- CSU System ----
  "san diego state":   { name:"San Diego State",     fullName:"San Diego State University",         tuition: 7798, type:"Public", state:"CA", city:"San Diego",         domain:"sdsu.edu" },
  "sdsu":              { name:"SDSU",                fullName:"San Diego State University",          tuition: 7798, type:"Public", state:"CA", city:"San Diego",         domain:"sdsu.edu" },
  "cal poly":          { name:"Cal Poly SLO",        fullName:"Cal Poly San Luis Obispo",           tuition: 9432, type:"Public", state:"CA", city:"San Luis Obispo",   domain:"calpoly.edu" },
  "cal poly slo":      { name:"Cal Poly SLO",        fullName:"Cal Poly San Luis Obispo",           tuition: 9432, type:"Public", state:"CA", city:"San Luis Obispo",   domain:"calpoly.edu" },
  "fresno state":      { name:"Fresno State",        fullName:"California State University Fresno", tuition: 7288, type:"Public", state:"CA", city:"Fresno",            domain:"fresnostate.edu" },
  "cal state la":      { name:"Cal State LA",        fullName:"California State University Los Angeles", tuition: 7096, type:"Public", state:"CA", city:"Los Angeles",  domain:"calstatela.edu" },
  "csulb":             { name:"CSULB",               fullName:"California State University Long Beach", tuition: 7138, type:"Public", state:"CA", city:"Long Beach",    domain:"csulb.edu" },
  "long beach state":  { name:"CSULB",               fullName:"California State University Long Beach", tuition: 7138, type:"Public", state:"CA", city:"Long Beach",    domain:"csulb.edu" },
  "sacramento state":  { name:"Sacramento State",    fullName:"California State University Sacramento", tuition: 7420, type:"Public", state:"CA", city:"Sacramento",    domain:"csus.edu" },
  "humboldt":          { name:"Cal Poly Humboldt",   fullName:"Cal Poly Humboldt",                  tuition: 7062, type:"Public", state:"CA", city:"Arcata",            domain:"humboldt.edu" },

  // ---- HBCUs ----
  "howard":            { name:"Howard",              fullName:"Howard University",                  tuition:29564, type:"Private Non-Profit", state:"DC", city:"Washington",      domain:"howard.edu" },
  "spelman":           { name:"Spelman",             fullName:"Spelman College",                    tuition:30040, type:"Private Non-Profit", state:"GA", city:"Atlanta",          domain:"spelman.edu" },
  "morehouse":         { name:"Morehouse",           fullName:"Morehouse College",                  tuition:30424, type:"Private Non-Profit", state:"GA", city:"Atlanta",          domain:"morehouse.edu" },
  "hampton":           { name:"Hampton",             fullName:"Hampton University",                 tuition:28412, type:"Private Non-Profit", state:"VA", city:"Hampton",          domain:"hamptonu.edu" },
  "florida a&m":       { name:"Florida A&M",         fullName:"Florida A&M University",             tuition: 5785, type:"Public", state:"FL", city:"Tallahassee",       domain:"famu.edu" },
  "famu":              { name:"FAMU",                fullName:"Florida A&M University",             tuition: 5785, type:"Public", state:"FL", city:"Tallahassee",       domain:"famu.edu" },
  "north carolina a&t": { name:"NC A&T",             fullName:"North Carolina A&T State University", tuition: 7429, type:"Public", state:"NC", city:"Greensboro",       domain:"ncat.edu" },
  "nc a&t":            { name:"NC A&T",              fullName:"North Carolina A&T State University", tuition: 7429, type:"Public", state:"NC", city:"Greensboro",       domain:"ncat.edu" },
  "prairie view a&m":  { name:"Prairie View A&M",    fullName:"Prairie View A&M University",        tuition: 7718, type:"Public", state:"TX", city:"Prairie View",      domain:"pvamu.edu" },
  "morgan state":      { name:"Morgan State",        fullName:"Morgan State University",            tuition: 7904, type:"Public", state:"MD", city:"Baltimore",         domain:"morgan.edu" },
  "xavier":            { name:"Xavier",              fullName:"Xavier University of Louisiana",     tuition:23450, type:"Private Non-Profit", state:"LA", city:"New Orleans",     domain:"xula.edu" },
  "tuskegee":          { name:"Tuskegee",            fullName:"Tuskegee University",                tuition:22440, type:"Private Non-Profit", state:"AL", city:"Tuskegee",        domain:"tuskegee.edu" },
  "clark atlanta":     { name:"Clark Atlanta",       fullName:"Clark Atlanta University",           tuition:27230, type:"Private Non-Profit", state:"GA", city:"Atlanta",          domain:"cau.edu" },
  "grambling":         { name:"Grambling",           fullName:"Grambling State University",         tuition: 7640, type:"Public", state:"LA", city:"Grambling",         domain:"gram.edu" },
  "southern":          { name:"Southern",            fullName:"Southern University and A&M",        tuition: 7590, type:"Public", state:"LA", city:"Baton Rouge",       domain:"sus.edu" },

  // ---- Liberal Arts Colleges ----
  "williams":          { name:"Williams",            fullName:"Williams College",                   tuition:61770, type:"Private Non-Profit", state:"MA", city:"Williamstown",    domain:"williams.edu" },
  "amherst":           { name:"Amherst",             fullName:"Amherst College",                    tuition:62700, type:"Private Non-Profit", state:"MA", city:"Amherst",         domain:"amherst.edu" },
  "swarthmore":        { name:"Swarthmore",          fullName:"Swarthmore College",                 tuition:56764, type:"Private Non-Profit", state:"PA", city:"Swarthmore",      domain:"swarthmore.edu" },
  "pomona":            { name:"Pomona",              fullName:"Pomona College",                     tuition:57892, type:"Private Non-Profit", state:"CA", city:"Claremont",        domain:"pomona.edu" },
  "wellesley":         { name:"Wellesley",           fullName:"Wellesley College",                  tuition:58214, type:"Private Non-Profit", state:"MA", city:"Wellesley",        domain:"wellesley.edu" },
  "vassar":            { name:"Vassar",              fullName:"Vassar College",                     tuition:60630, type:"Private Non-Profit", state:"NY", city:"Poughkeepsie",     domain:"vassar.edu" },
  "bowdoin":           { name:"Bowdoin",             fullName:"Bowdoin College",                    tuition:58860, type:"Private Non-Profit", state:"ME", city:"Brunswick",        domain:"bowdoin.edu" },
  "middlebury":        { name:"Middlebury",          fullName:"Middlebury College",                 tuition:60116, type:"Private Non-Profit", state:"VT", city:"Middlebury",       domain:"middlebury.edu" },
  "colby":             { name:"Colby",               fullName:"Colby College",                      tuition:58230, type:"Private Non-Profit", state:"ME", city:"Waterville",       domain:"colby.edu" },
  "bates":             { name:"Bates",               fullName:"Bates College",                      tuition:60210, type:"Private Non-Profit", state:"ME", city:"Lewiston",         domain:"bates.edu" },
  "hamilton":          { name:"Hamilton",            fullName:"Hamilton College",                   tuition:60710, type:"Private Non-Profit", state:"NY", city:"Clinton",          domain:"hamilton.edu" },
  "colgate":           { name:"Colgate",             fullName:"Colgate University",                 tuition:60600, type:"Private Non-Profit", state:"NY", city:"Hamilton",         domain:"colgate.edu" },
  "carleton":          { name:"Carleton",            fullName:"Carleton College",                   tuition:59562, type:"Private Non-Profit", state:"MN", city:"Northfield",       domain:"carleton.edu" },
  "grinnell":          { name:"Grinnell",            fullName:"Grinnell College",                   tuition:54850, type:"Private Non-Profit", state:"IA", city:"Grinnell",         domain:"grinnell.edu" },
  "oberlin":           { name:"Oberlin",             fullName:"Oberlin College",                    tuition:59488, type:"Private Non-Profit", state:"OH", city:"Oberlin",          domain:"oberlin.edu" },
  "macalester":        { name:"Macalester",          fullName:"Macalester College",                 tuition:57788, type:"Private Non-Profit", state:"MN", city:"Saint Paul",       domain:"macalester.edu" },
  "haverford":         { name:"Haverford",           fullName:"Haverford College",                  tuition:58050, type:"Private Non-Profit", state:"PA", city:"Haverford",        domain:"haverford.edu" },
  "bryn mawr":         { name:"Bryn Mawr",           fullName:"Bryn Mawr College",                  tuition:56134, type:"Private Non-Profit", state:"PA", city:"Bryn Mawr",        domain:"brynmawr.edu" },
  "barnard":           { name:"Barnard",             fullName:"Barnard College",                    tuition:58882, type:"Private Non-Profit", state:"NY", city:"New York City",    domain:"barnard.edu" },
  "smith":             { name:"Smith",               fullName:"Smith College",                      tuition:57504, type:"Private Non-Profit", state:"MA", city:"Northampton",      domain:"smith.edu" },
  "mount holyoke":     { name:"Mount Holyoke",       fullName:"Mount Holyoke College",              tuition:54320, type:"Private Non-Profit", state:"MA", city:"South Hadley",     domain:"mtholyoke.edu" },
  "colorado college":  { name:"Colorado College",    fullName:"Colorado College",                   tuition:57078, type:"Private Non-Profit", state:"CO", city:"Colorado Springs", domain:"coloradocollege.edu" },
  "trinity":           { name:"Trinity",             fullName:"Trinity College",                    tuition:61188, type:"Private Non-Profit", state:"CT", city:"Hartford",         domain:"trincoll.edu" },
  "dickinson":         { name:"Dickinson",           fullName:"Dickinson College",                  tuition:56832, type:"Private Non-Profit", state:"PA", city:"Carlisle",         domain:"dickinson.edu" },
  "denison":           { name:"Denison",             fullName:"Denison University",                 tuition:55020, type:"Private Non-Profit", state:"OH", city:"Granville",        domain:"denison.edu" },
  "skidmore":          { name:"Skidmore",            fullName:"Skidmore College",                   tuition:58394, type:"Private Non-Profit", state:"NY", city:"Saratoga Springs",  domain:"skidmore.edu" },
  "union":             { name:"Union",               fullName:"Union College",                      tuition:59535, type:"Private Non-Profit", state:"NY", city:"Schenectady",      domain:"union.edu" },
  "lafayette":         { name:"Lafayette",           fullName:"Lafayette College",                  tuition:58010, type:"Private Non-Profit", state:"PA", city:"Easton",           domain:"lafayette.edu" },
  "furman":            { name:"Furman",              fullName:"Furman University",                  tuition:53346, type:"Private Non-Profit", state:"SC", city:"Greenville",       domain:"furman.edu" },
  "rhodes":            { name:"Rhodes",              fullName:"Rhodes College",                     tuition:49432, type:"Private Non-Profit", state:"TN", city:"Memphis",          domain:"rhodes.edu" },
  "davidson":          { name:"Davidson",            fullName:"Davidson College",                   tuition:56064, type:"Private Non-Profit", state:"NC", city:"Davidson",         domain:"davidson.edu" },

  // ---- Tech Schools ----
  "wpi":               { name:"WPI",                 fullName:"Worcester Polytechnic Institute",    tuition:56870, type:"Private Non-Profit", state:"MA", city:"Worcester",        domain:"wpi.edu" },
  "worcester polytechnic": { name:"WPI",             fullName:"Worcester Polytechnic Institute",    tuition:56870, type:"Private Non-Profit", state:"MA", city:"Worcester",        domain:"wpi.edu" },
  "rose-hulman":       { name:"Rose-Hulman",         fullName:"Rose-Hulman Institute of Technology", tuition:56325, type:"Private Non-Profit", state:"IN", city:"Terre Haute",     domain:"rose-hulman.edu" },
  "clarkson":          { name:"Clarkson",            fullName:"Clarkson University",                tuition:54360, type:"Private Non-Profit", state:"NY", city:"Potsdam",          domain:"clarkson.edu" },
  "stevens institute": { name:"Stevens",             fullName:"Stevens Institute of Technology",    tuition:56926, type:"Private Non-Profit", state:"NJ", city:"Hoboken",          domain:"stevens.edu" },
  "njit":              { name:"NJIT",                fullName:"New Jersey Institute of Technology", tuition:17418, type:"Public",             state:"NJ", city:"Newark",           domain:"njit.edu" },
  "michigan tech":     { name:"Michigan Tech",       fullName:"Michigan Technological University",  tuition:16702, type:"Public", state:"MI", city:"Houghton",          domain:"mtu.edu" },
  "virginia tech":     { name:"Virginia Tech",       fullName:"Virginia Tech",                      tuition:14006, type:"Public", state:"VA", city:"Blacksburg",        domain:"vt.edu" },
  "nc state":          { name:"NC State",            fullName:"NC State University",                tuition: 9100, type:"Public", state:"NC", city:"Raleigh",           domain:"ncsu.edu" },
  "north carolina state": { name:"NC State",         fullName:"NC State University",                tuition: 9100, type:"Public", state:"NC", city:"Raleigh",           domain:"ncsu.edu" },
  "texas a&m":         { name:"Texas A&M",           fullName:"Texas A&M University",               tuition:10886, type:"Public", state:"TX", city:"College Station",   domain:"tamu.edu" },
  "tamu":              { name:"Texas A&M",           fullName:"Texas A&M University",               tuition:10886, type:"Public", state:"TX", city:"College Station",   domain:"tamu.edu" },
  "colorado school of mines": { name:"Colorado Mines", fullName:"Colorado School of Mines",         tuition:18810, type:"Public", state:"CO", city:"Golden",            domain:"mines.edu" },

  // ---- More State Schools ----
  "bowling green":     { name:"Bowling Green",       fullName:"Bowling Green State University",     tuition:10614, type:"Public", state:"OH", city:"Bowling Green",     domain:"bgsu.edu" },
  "miami university":  { name:"Miami University",    fullName:"Miami University",                   tuition:16069, type:"Public", state:"OH", city:"Oxford",            domain:"miamioh.edu" },
  "kent state":        { name:"Kent State",          fullName:"Kent State University",              tuition:11388, type:"Public", state:"OH", city:"Kent",              domain:"kent.edu" },
  "akron":             { name:"Akron",               fullName:"University of Akron",                tuition:11290, type:"Public", state:"OH", city:"Akron",             domain:"uakron.edu" },
  "toledo":            { name:"Toledo",              fullName:"University of Toledo",               tuition:11048, type:"Public", state:"OH", city:"Toledo",            domain:"utoledo.edu" },
  "wright state":      { name:"Wright State",        fullName:"Wright State University",            tuition: 9480, type:"Public", state:"OH", city:"Dayton",            domain:"wright.edu" },
  "ball state":        { name:"Ball State",          fullName:"Ball State University",              tuition:10012, type:"Public", state:"IN", city:"Muncie",            domain:"bsu.edu" },
  "depaul":            { name:"DePaul",              fullName:"DePaul University",                  tuition:42912, type:"Private Non-Profit", state:"IL", city:"Chicago",         domain:"depaul.edu" },
  "loyola chicago":    { name:"Loyola Chicago",      fullName:"Loyola University Chicago",          tuition:48670, type:"Private Non-Profit", state:"IL", city:"Chicago",         domain:"luc.edu" },
  "marquette":         { name:"Marquette",           fullName:"Marquette University",               tuition:44100, type:"Private Non-Profit", state:"WI", city:"Milwaukee",       domain:"marquette.edu" },
  "wisconsin":         { name:"Wisconsin",           fullName:"University of Wisconsin-Madison",    tuition:10728, type:"Public", state:"WI", city:"Madison",           domain:"wisc.edu" },
  "uw madison":        { name:"UW-Madison",          fullName:"University of Wisconsin-Madison",    tuition:10728, type:"Public", state:"WI", city:"Madison",           domain:"wisc.edu" },
  "wisconsin milwaukee": { name:"UW-Milwaukee",      fullName:"University of Wisconsin-Milwaukee",  tuition: 9592, type:"Public", state:"WI", city:"Milwaukee",         domain:"uwm.edu" },
  "marquette university": { name:"Marquette",        fullName:"Marquette University",               tuition:44100, type:"Private Non-Profit", state:"WI", city:"Milwaukee",      domain:"marquette.edu" },
  "xavier university": { name:"Xavier Ohio",         fullName:"Xavier University",                  tuition:43030, type:"Private Non-Profit", state:"OH", city:"Cincinnati",      domain:"xavier.edu" },
  "cincinnati":        { name:"Cincinnati",          fullName:"University of Cincinnati",           tuition:12678, type:"Public", state:"OH", city:"Cincinnati",        domain:"uc.edu" },
  "george mason":      { name:"George Mason",        fullName:"George Mason University",            tuition:13182, type:"Public", state:"VA", city:"Fairfax",           domain:"gmu.edu" },
  "james madison":     { name:"James Madison",       fullName:"James Madison University",           tuition: 8278, type:"Public", state:"VA", city:"Harrisonburg",      domain:"jmu.edu" },
  "old dominion":      { name:"Old Dominion",        fullName:"Old Dominion University",            tuition:10224, type:"Public", state:"VA", city:"Norfolk",           domain:"odu.edu" },
  "vcu":               { name:"VCU",                 fullName:"Virginia Commonwealth University",   tuition:14472, type:"Public", state:"VA", city:"Richmond",          domain:"vcu.edu" },
  "william and mary":  { name:"William & Mary",      fullName:"College of William & Mary",          tuition:21204, type:"Public", state:"VA", city:"Williamsburg",      domain:"wm.edu" },
  "william & mary":    { name:"William & Mary",      fullName:"College of William & Mary",          tuition:21204, type:"Public", state:"VA", city:"Williamsburg",      domain:"wm.edu" },
  "temple":            { name:"Temple",              fullName:"Temple University",                  tuition:17376, type:"Public", state:"PA", city:"Philadelphia",      domain:"temple.edu" },
  "west chester":      { name:"West Chester",        fullName:"West Chester University",            tuition:10260, type:"Public", state:"PA", city:"West Chester",      domain:"wcupa.edu" },
  "kutztown":          { name:"Kutztown",            fullName:"Kutztown University",                tuition: 9720, type:"Public", state:"PA", city:"Kutztown",          domain:"kutztown.edu" },
  "suny stony brook":  { name:"Stony Brook",         fullName:"SUNY Stony Brook",                   tuition: 9657, type:"Public", state:"NY", city:"Stony Brook",       domain:"stonybrook.edu" },
  "stony brook":       { name:"Stony Brook",         fullName:"SUNY Stony Brook",                   tuition: 9657, type:"Public", state:"NY", city:"Stony Brook",       domain:"stonybrook.edu" },
  "suny buffalo":      { name:"UB",                  fullName:"SUNY University at Buffalo",         tuition:10112, type:"Public", state:"NY", city:"Buffalo",           domain:"buffalo.edu" },
  "buffalo":           { name:"UB",                  fullName:"SUNY University at Buffalo",         tuition:10112, type:"Public", state:"NY", city:"Buffalo",           domain:"buffalo.edu" },
  "suny albany":       { name:"Albany",              fullName:"SUNY Albany",                        tuition: 9653, type:"Public", state:"NY", city:"Albany",            domain:"albany.edu" },
  "binghamton":        { name:"Binghamton",          fullName:"SUNY Binghamton",                    tuition:10127, type:"Public", state:"NY", city:"Binghamton",        domain:"binghamton.edu" },
  "suny binghamton":   { name:"Binghamton",          fullName:"SUNY Binghamton",                    tuition:10127, type:"Public", state:"NY", city:"Binghamton",        domain:"binghamton.edu" },
  "hofstra":           { name:"Hofstra",             fullName:"Hofstra University",                 tuition:53380, type:"Private Non-Profit", state:"NY", city:"Hempstead",        domain:"hofstra.edu" },
  "adelphi":           { name:"Adelphi",             fullName:"Adelphi University",                 tuition:43480, type:"Private Non-Profit", state:"NY", city:"Garden City",      domain:"adelphi.edu" },
  "pace":              { name:"Pace",                fullName:"Pace University",                    tuition:44490, type:"Private Non-Profit", state:"NY", city:"New York City",    domain:"pace.edu" },
  "st john's":         { name:"St. John's",          fullName:"St. John's University",              tuition:43960, type:"Private Non-Profit", state:"NY", city:"Queens",           domain:"stjohns.edu" },
  "seton hall":        { name:"Seton Hall",          fullName:"Seton Hall University",              tuition:43840, type:"Private Non-Profit", state:"NJ", city:"South Orange",     domain:"shu.edu" },
  "fairfield":         { name:"Fairfield",           fullName:"Fairfield University",               tuition:51560, type:"Private Non-Profit", state:"CT", city:"Fairfield",        domain:"fairfield.edu" },
  "sacred heart":      { name:"Sacred Heart",        fullName:"Sacred Heart University",            tuition:45040, type:"Private Non-Profit", state:"CT", city:"Fairfield",        domain:"sacredheart.edu" },
  "quinnipiac":        { name:"Quinnipiac",          fullName:"Quinnipiac University",              tuition:48200, type:"Private Non-Profit", state:"CT", city:"Hamden",           domain:"quinnipiac.edu" },
  "gonzaga":           { name:"Gonzaga",             fullName:"Gonzaga University",                 tuition:50388, type:"Private Non-Profit", state:"WA", city:"Spokane",          domain:"gonzaga.edu" },
  "seattle university": { name:"Seattle University", fullName:"Seattle University",                 tuition:49374, type:"Private Non-Profit", state:"WA", city:"Seattle",          domain:"seattleu.edu" },
  "santa clara":       { name:"Santa Clara",         fullName:"Santa Clara University",             tuition:57264, type:"Private Non-Profit", state:"CA", city:"Santa Clara",      domain:"scu.edu" },
  "loyola marymount":  { name:"LMU",                 fullName:"Loyola Marymount University",        tuition:56048, type:"Private Non-Profit", state:"CA", city:"Los Angeles",      domain:"lmu.edu" },
  "lmu":               { name:"LMU",                 fullName:"Loyola Marymount University",        tuition:56048, type:"Private Non-Profit", state:"CA", city:"Los Angeles",      domain:"lmu.edu" },
  "pepperdine":        { name:"Pepperdine",          fullName:"Pepperdine University",              tuition:60392, type:"Private Non-Profit", state:"CA", city:"Malibu",           domain:"pepperdine.edu" },
  "university of san francisco": { name:"USF",       fullName:"University of San Francisco",        tuition:55940, type:"Private Non-Profit", state:"CA", city:"San Francisco",    domain:"usfca.edu" },
  "usf":               { name:"USF",                 fullName:"University of San Francisco",        tuition:55940, type:"Private Non-Profit", state:"CA", city:"San Francisco",    domain:"usfca.edu" },
  "university of san diego": { name:"USD",           fullName:"University of San Diego",            tuition:56200, type:"Private Non-Profit", state:"CA", city:"San Diego",        domain:"sandiego.edu" },
  "usd":               { name:"USD",                 fullName:"University of San Diego",            tuition:56200, type:"Private Non-Profit", state:"CA", city:"San Diego",        domain:"sandiego.edu" },
  "creighton":         { name:"Creighton",           fullName:"Creighton University",               tuition:42910, type:"Private Non-Profit", state:"NE", city:"Omaha",            domain:"creighton.edu" },
  "depauw":            { name:"DePauw",              fullName:"DePauw University",                  tuition:46800, type:"Private Non-Profit", state:"IN", city:"Greencastle",      domain:"depauw.edu" },
  "butler":            { name:"Butler",              fullName:"Butler University",                  tuition:43480, type:"Private Non-Profit", state:"IN", city:"Indianapolis",     domain:"butler.edu" },
  "elon":              { name:"Elon",                fullName:"Elon University",                    tuition:38810, type:"Private Non-Profit", state:"NC", city:"Elon",             domain:"elon.edu" },
  "high point":        { name:"High Point",          fullName:"High Point University",              tuition:37200, type:"Private Non-Profit", state:"NC", city:"High Point",       domain:"highpoint.edu" },
  "belmont":           { name:"Belmont",             fullName:"Belmont University",                 tuition:33700, type:"Private Non-Profit", state:"TN", city:"Nashville",        domain:"belmont.edu" },
  "lipscomb":          { name:"Lipscomb",            fullName:"Lipscomb University",                tuition:32498, type:"Private Non-Profit", state:"TN", city:"Nashville",        domain:"lipscomb.edu" },
  "samford":           { name:"Samford",             fullName:"Samford University",                 tuition:31836, type:"Private Non-Profit", state:"AL", city:"Birmingham",       domain:"samford.edu" },
  "ouachita baptist":  { name:"Ouachita Baptist",    fullName:"Ouachita Baptist University",        tuition:26800, type:"Private Non-Profit", state:"AR", city:"Arkadelphia",     domain:"obu.edu" },
  "baylor":            { name:"Baylor",              fullName:"Baylor University",                  tuition:52006, type:"Private Non-Profit", state:"TX", city:"Waco",             domain:"baylor.edu" },
  "tcu":               { name:"TCU",                 fullName:"Texas Christian University",         tuition:52230, type:"Private Non-Profit", state:"TX", city:"Fort Worth",       domain:"tcu.edu" },
  "texas christian":   { name:"TCU",                 fullName:"Texas Christian University",         tuition:52230, type:"Private Non-Profit", state:"TX", city:"Fort Worth",       domain:"tcu.edu" },
  "smu":               { name:"SMU",                 fullName:"Southern Methodist University",      tuition:59690, type:"Private Non-Profit", state:"TX", city:"Dallas",           domain:"smu.edu" },
  "southern methodist": { name:"SMU",                fullName:"Southern Methodist University",      tuition:59690, type:"Private Non-Profit", state:"TX", city:"Dallas",           domain:"smu.edu" },
  "texas tech":        { name:"Texas Tech",          fullName:"Texas Tech University",              tuition:11850, type:"Public", state:"TX", city:"Lubbock",           domain:"ttu.edu" },
  "byu":               { name:"BYU",                 fullName:"Brigham Young University",           tuition: 6120, type:"Private Non-Profit", state:"UT", city:"Provo",           domain:"byu.edu" },
  "brigham young":     { name:"BYU",                 fullName:"Brigham Young University",           tuition: 6120, type:"Private Non-Profit", state:"UT", city:"Provo",           domain:"byu.edu" },
  "boise state":       { name:"Boise State",         fullName:"Boise State University",             tuition: 7992, type:"Public", state:"ID", city:"Boise",             domain:"boisestate.edu" },

  // ---- New England ----
  "babson":            { name:"Babson",              fullName:"Babson College",                     tuition:55696, type:"Private Non-Profit", state:"MA", city:"Babson Park",      domain:"babson.edu" },
  "bentley":           { name:"Bentley",             fullName:"Bentley University",                 tuition:53650, type:"Private Non-Profit", state:"MA", city:"Waltham",         domain:"bentley.edu" },
  "clark":             { name:"Clark",               fullName:"Clark University",                   tuition:48480, type:"Private Non-Profit", state:"MA", city:"Worcester",        domain:"clarku.edu" },
  "suffolk":           { name:"Suffolk",             fullName:"Suffolk University",                 tuition:40000, type:"Private Non-Profit", state:"MA", city:"Boston",           domain:"suffolk.edu" },
  "wheaton":           { name:"Wheaton",             fullName:"Wheaton College",                    tuition:58386, type:"Private Non-Profit", state:"MA", city:"Norton",           domain:"wheatonma.edu" },
  "stonehill":         { name:"Stonehill",           fullName:"Stonehill College",                  tuition:44954, type:"Private Non-Profit", state:"MA", city:"Easton",           domain:"stonehill.edu" },
  "merrimack":         { name:"Merrimack",           fullName:"Merrimack College",                  tuition:42930, type:"Private Non-Profit", state:"MA", city:"North Andover",    domain:"merrimack.edu" },
  "regis":             { name:"Regis",               fullName:"Regis College",                      tuition:41408, type:"Private Non-Profit", state:"MA", city:"Weston",           domain:"regiscollege.edu" },
  "assumption":        { name:"Assumption",          fullName:"Assumption University",              tuition:38736, type:"Private Non-Profit", state:"MA", city:"Worcester",        domain:"assumption.edu" },
  "umass amherst":     { name:"UMass Amherst",       fullName:"University of Massachusetts Amherst", tuition:16722, type:"Public", state:"MA", city:"Amherst",          domain:"umass.edu" },
  "umass boston":      { name:"UMass Boston",        fullName:"University of Massachusetts Boston", tuition:15412, type:"Public", state:"MA", city:"Boston",            domain:"umb.edu" },
  "umass lowell":      { name:"UMass Lowell",        fullName:"University of Massachusetts Lowell", tuition:16227, type:"Public", state:"MA", city:"Lowell",            domain:"uml.edu" },
};

// ============================================
// SCHOOL DOMAINS (for logo lookup via Clearbit)
// ============================================
const SCHOOL_DOMAINS = {};
Object.entries(SCHOOLS).forEach(([key, school]) => {
  if (school.domain) {
    SCHOOL_DOMAINS[key] = school.domain;
    SCHOOL_DOMAINS[(school.fullName || school.name).toLowerCase()] = school.domain;
  }
});

// ============================================
// COMPREHENSIVE SCHOOL NAMES LIST (~500+)
// Used for autocomplete suggestions
// ============================================
const SCHOOL_NAMES_LIST = [
  // Ivy League
  "Harvard University","Yale University","Princeton University","Columbia University",
  "University of Pennsylvania","Dartmouth College","Brown University","Cornell University",
  // Elite Private
  "MIT","Stanford University","California Institute of Technology","Duke University",
  "Northwestern University","Vanderbilt University","University of Chicago","University of Notre Dame",
  "Johns Hopkins University","Tufts University","Carnegie Mellon University","Emory University",
  "Rice University","Wake Forest University","Georgetown University","New York University",
  "Boston University","Boston College","Tulane University","Lehigh University",
  "Fordham University","Villanova University","University of Rochester",
  "Case Western Reserve University","American University","Brandeis University",
  "Rensselaer Polytechnic Institute","Northeastern University","Drexel University",
  "George Washington University","University of Southern California",
  // Flagship Publics
  "Ohio State University","University of Michigan","UNC Chapel Hill","University of Virginia",
  "Georgia Institute of Technology","University of Florida","University of Texas at Austin",
  "Arizona State University","Purdue University","Penn State University",
  "University of Illinois Urbana-Champaign","University of Minnesota","University of Maryland",
  "Rutgers University","University of Colorado Boulder","University of Iowa",
  "Iowa State University","Indiana University Bloomington","Michigan State University",
  "University of Pittsburgh","University of Kentucky","University of Tennessee",
  "University of Georgia","Auburn University","University of Alabama",
  "University of South Carolina","Clemson University","Florida State University",
  "University of Washington","University of Oregon","Oregon State University",
  "University of Utah","University of Nebraska-Lincoln","University of Kansas",
  "Kansas State University","University of Missouri","University of Arkansas",
  "University of Mississippi","Mississippi State University","Louisiana State University",
  "University of Oklahoma","Oklahoma State University","Colorado State University",
  "University of New Mexico","University of Nevada Reno","University of Nevada Las Vegas",
  "University of Idaho","University of Montana","University of Wyoming",
  "University of North Dakota","University of South Dakota","West Virginia University",
  "University of Delaware","University of Connecticut","University of Rhode Island",
  "University of New Hampshire","University of Maine","University of Vermont",
  "University of Hawaii at Manoa","University of Alaska Fairbanks",
  "University of Miami","University of Wisconsin-Madison","University of Cincinnati",
  // UC System
  "UCLA","UC Berkeley","UC San Diego","UC Irvine","UC Santa Barbara",
  "UC Davis","UC Riverside","UC Santa Cruz","UC Merced",
  // CSU System
  "San Diego State University","Cal Poly San Luis Obispo","Cal Poly Pomona",
  "California State University Fresno","California State University Long Beach",
  "California State University Los Angeles","California State University Sacramento",
  "California State University Northridge","California State University Fullerton",
  "California State University East Bay","California State University San Bernardino",
  "California State University Bakersfield","California State University Stanislaus",
  "California State University Dominguez Hills","Cal Poly Humboldt",
  "San Francisco State University","San Jose State University",
  "Sonoma State University","Chico State University","Cal Maritime",
  // HBCUs
  "Howard University","Spelman College","Morehouse College","Hampton University",
  "Florida A&M University","North Carolina A&T State University",
  "Prairie View A&M University","Morgan State University",
  "Xavier University of Louisiana","Tuskegee University","Clark Atlanta University",
  "Grambling State University","Southern University and A&M","Alcorn State University",
  "Bethune-Cookman University","Delaware State University","Fisk University",
  "Fort Valley State University","Jackson State University","Lincoln University",
  "Norfolk State University","Savannah State University","South Carolina State University",
  "Tennessee State University","Texas Southern University","Virginia State University",
  "Virginia Union University","Winston-Salem State University",
  "Alabama A&M University","Alabama State University","Bowie State University",
  "Central State University","Cheyney University","Coppin State University",
  "Elizabeth City State University","Langston University","Meharry Medical College",
  "Miles College","Shaw University","Stillman College","Talladega College",
  // Liberal Arts
  "Williams College","Amherst College","Swarthmore College","Pomona College",
  "Wellesley College","Vassar College","Bowdoin College","Middlebury College",
  "Colby College","Bates College","Hamilton College","Colgate University",
  "Carleton College","Grinnell College","Oberlin College","Macalester College",
  "Haverford College","Bryn Mawr College","Barnard College","Smith College",
  "Mount Holyoke College","Colorado College","Trinity College","Dickinson College",
  "Denison University","Skidmore College","Union College","Lafayette College",
  "Furman University","Rhodes College","Davidson College","Kenyon College",
  "Wabash College","Wheaton College (IL)","Kalamazoo College","Beloit College",
  "Lawrence University","St. Olaf College","Luther College","Gustavus Adolphus College",
  "Augustana College","Hope College","Calvin University","Albion College",
  "Alma College","Adrian College","Hillsdale College","Allegheny College",
  "Gettysburg College","Ursinus College","Muhlenberg College","Susquehanna University",
  "Elizabethtown College","Franklin and Marshall College","Juniata College",
  "Lycoming College","Messiah University","Slippery Rock University",
  "Bard College","Hobart and William Smith Colleges","Wells College","Keuka College",
  "Hartwick College","Alfred University","Clarkson University","Elmira College",
  "Ithaca College","Le Moyne College","Manhattan College","Manhattanville College",
  "Marist College","Mercy University","Molloy University","Monmouth University",
  "New Paltz State University","Niagara University","Oswego State University",
  "Plattsburgh State University","Purchase College","Utica University",
  "Wagner College","St. Lawrence University","Sarah Lawrence College",
  // Tech Schools
  "Worcester Polytechnic Institute","Rose-Hulman Institute of Technology",
  "Stevens Institute of Technology","New Jersey Institute of Technology",
  "Michigan Technological University","Virginia Tech","NC State University",
  "Texas A&M University","Colorado School of Mines",
  // Southern & Regional
  "Baylor University","Texas Christian University","Southern Methodist University",
  "Texas Tech University","Brigham Young University","Boise State University",
  "Utah State University","Idaho State University","Montana State University",
  "New Mexico State University","Nevada State University",
  "Sam Houston State University","Stephen F. Austin State University",
  "Texas State University","University of Houston","University of North Texas",
  "University of Texas at Dallas","University of Texas at El Paso",
  "University of Texas at San Antonio","Lamar University",
  "George Mason University","James Madison University","Old Dominion University",
  "Virginia Commonwealth University","College of William & Mary","Radford University",
  "Longwood University","Shenandoah University","Christopher Newport University",
  "Elon University","High Point University","Appalachian State University",
  "East Carolina University","Western Carolina University","Wingate University",
  "Gardner-Webb University","Belmont University","Lipscomb University",
  "Samford University","Troy University","University of North Alabama",
  "Jacksonville State University","University of Montevallo",
  "Georgia State University","Georgia Southern University",
  "Columbus State University","Kennesaw State University",
  "Valdosta State University","Fort Valley State University",
  "Armstrong State University","Berry College","Mercer University",
  "University of Louisiana Lafayette","Southeastern Louisiana University",
  "University of Louisiana Monroe","Northwestern State University",
  "McNeese State University","Nicholls State University",
  "University of South Alabama","Spring Hill College","Huntingdon College",
  "Freed-Hardeman University","Austin Peay State University",
  "Middle Tennessee State University","Tennessee Tech University",
  "East Tennessee State University","Western Kentucky University",
  "Eastern Kentucky University","Morehead State University","Murray State University",
  "Northern Kentucky University","Campbellsville University","Cumberland University",
  "Bellarmine University","Transylvania University","Centre College",
  "University of Louisville","Marshall University","Shepherd University",
  "Fairmont State University","Concord University","Bluefield State University",
  // Midwest
  "Ball State University","Indiana State University","IUPUI","Valparaiso University",
  "Saint Mary's College","Goshen College","Taylor University","Hanover College",
  "University of Evansville","DePauw University","Wabash College","Butler University",
  "DePaul University","Loyola University Chicago","Illinois Institute of Technology",
  "Northwestern College","Wheaton College (IL)","Millikin University",
  "Bradley University","Augustana College (IL)","Illinois Wesleyan University",
  "Lake Forest College","Knox College","Monmouth College","MacMurray College",
  "Eastern Illinois University","Illinois State University","Northern Illinois University",
  "Western Illinois University","Southern Illinois University Carbondale",
  "Southern Illinois University Edwardsville","University of Missouri-St. Louis",
  "Missouri State University","Truman State University","Missouri University of Science and Technology",
  "Drury University","Saint Louis University","Webster University","Lindenwood University",
  "College of the Ozarks","Fontbonne University","Maryville University",
  "University of Minnesota Duluth","Minnesota State University Mankato",
  "St. Cloud State University","Winona State University","Bemidji State University",
  "Metropolitan State University","University of St. Thomas","St. John's University (MN)",
  "College of St. Benedict","Concordia College","Hamline University",
  "University of Wisconsin-Milwaukee","University of Wisconsin-Eau Claire",
  "University of Wisconsin-La Crosse","University of Wisconsin-Oshkosh",
  "University of Wisconsin-Stevens Point","University of Wisconsin-Stout",
  "University of Wisconsin-Superior","University of Wisconsin-Platteville",
  "University of Wisconsin-River Falls","University of Wisconsin-Whitewater",
  "Marquette University","Alverno College","Carroll University","Carthage College",
  "Concordia University Wisconsin","Lakeland University","Lawrence University",
  "Marian University","Milwaukee School of Engineering","Mount Mary University",
  "Ripon College","St. Norbert College","Viterbo University",
  "University of Nebraska Omaha","University of Nebraska Kearney",
  "Creighton University","Doane University","Hastings College",
  "Nebraska Wesleyan University","Union College (NE)","Wayne State College",
  "Chadron State College","Peru State College","Midland University",
  "University of South Dakota","South Dakota State University",
  "South Dakota Mines","Northern State University","Black Hills State University",
  "Augustana University (SD)","Dakota Wesleyan University","Presentation College",
  "University of North Dakota","North Dakota State University",
  "Minot State University","Valley City State University","Dickinson State University",
  "Mayville State University","Jamestown University",
  "University of Iowa","Iowa State University","Drake University",
  "Coe College","Cornell College","Luther College","Wartburg College",
  "Simpson College","Loras College","Clarke University","Mount Mercy University",
  "St. Ambrose University","Briar Cliff University","Buena Vista University",
  "University of Kansas","Kansas State University","Wichita State University",
  "Washburn University","Fort Hays State University","Emporia State University",
  "Pittsburg State University","Friends University","Sterling College",
  "Bethel College","Tabor College","McPherson College","Ottawa University",
  // Northeast
  "Syracuse University","SUNY Stony Brook","SUNY University at Buffalo",
  "SUNY Albany","SUNY Binghamton","SUNY New Paltz","SUNY Oneonta",
  "SUNY Cortland","SUNY Plattsburgh","SUNY Oswego","SUNY Purchase",
  "Fordham University","Hofstra University","Adelphi University","Pace University",
  "St. John's University","Manhattan College","Manhattanville University",
  "Marist College","Niagara University","Canisius University","Le Moyne College",
  "Alfred University","Ithaca College","Hartwick College","Keuka College",
  "Utica University","Elmira College","Wells College","Skidmore College",
  "Wagner College","Seton Hall University","Fairfield University",
  "Sacred Heart University","Quinnipiac University","University of Bridgeport",
  "Southern Connecticut State University","Central Connecticut State University",
  "Eastern Connecticut State University","Western Connecticut State University",
  "Post University","Albertus Magnus College","Charter Oak State College",
  "University of Hartford","Providence College","Bryant University",
  "Johnson & Wales University","Roger Williams University",
  "Salve Regina University","Rhode Island College","Rhode Island School of Design",
  "Massachusetts College of Art","Emerson College","Berklee College of Music",
  "Lesley University","Emmanuel College","Simmons University",
  "Stonehill College","Merrimack College","Assumption University",
  "Anna Maria College","Bay Path University","Dean College",
  "Eastern Nazarene College","Endicott College","Fisher College",
  "Gordon College","Lasell University","Newbury College","Nichols College",
  "Regis College","Springfield College","Western New England University",
  "Westfield State University","Worcester State University","Framingham State University",
  "Bridgewater State University","Fitchburg State University",
  "Massachusetts Maritime Academy","Salem State University","North Shore Community College",
  "Bowdoin College","Colby College","Bates College","University of Maine",
  "University of Maine at Farmington","University of Southern Maine",
  "Saint Joseph's College (ME)","Husson University","Thomas College","Unity College",
  "University of Vermont","Middlebury College","Norwich University","Champlain College",
  "Saint Michael's College","Castleton University","Johnson State University",
  "Plymouth State University","Keene State College","Franklin Pierce University",
  "St. Anselm College","Southern New Hampshire University","New England College",
  "Colby-Sawyer College","Dartmouth College",
  "Pace University","Mercy University","College of Mount Saint Vincent",
  "Molloy University","Cabrini University","Chestnut Hill College",
  "Immaculata University","La Salle University","Philadelphia University",
  "Saint Joseph's University","Thomas Jefferson University",
  "West Chester University","Millersville University","Shippensburg University",
  "Kutztown University","Lock Haven University","Clarion University",
  "Indiana University of Pennsylvania","Edinboro University",
  "California University of Pennsylvania","Slippery Rock University",
  "University of Scranton","Marywood University","King's College",
  "Misericordia University","Wilkes University","College Misericordia",
  "Lycoming College","Bucknell University","Susquehanna University",
  "Elizabethtown College","Lebanon Valley College","Messiah University",
  "Gettysburg College","Dickinson College","Franklin and Marshall College",
  "Muhlenberg College","Ursinus College","Arcadia University","Arcadia University",
  "Neumann University","Gwynedd Mercy University","Salus University",
  "Delaware Valley University","Cedar Crest College","Alvernia University",
  "Cabrini University","Rosemont College",
  // Pacific Northwest & Mountain West
  "Gonzaga University","Seattle University","Pacific Lutheran University",
  "University of Puget Sound","Whitman College","Whitworth University",
  "Seattle Pacific University","Saint Martin's University","Western Washington University",
  "Central Washington University","Eastern Washington University",
  "Pacific University","Linfield University","Willamette University",
  "George Fox University","Corban University","Lewis & Clark College",
  "Reed College","Portland State University","Portland University",
  "University of Portland","Marylhurst University","Western Oregon University",
  "Eastern Oregon University","Southern Oregon University","Oregon Institute of Technology",
  "Boise State University","Idaho State University","Lewis-Clark State College",
  "Northwest Nazarene University","College of Idaho","Albertson College",
  "Montana State University","Montana Technological University","Rocky Mountain College",
  "Carroll College (MT)","University of Great Falls","Salish Kootenai College",
  "University of Wyoming","Laramie County Community College",
  "Colorado State University","University of Northern Colorado",
  "Colorado Mesa University","Metropolitan State University of Denver",
  "Fort Lewis College","Western Colorado University","Adams State University",
  "Mesa State College","Regis University","Colorado Christian University",
  "University of Denver","Colorado College","Air Force Academy",
  "Utah State University","Weber State University","Utah Valley University",
  "Southern Utah University","Dixie State University","Westminster College (UT)",
  "Snow College","Brigham Young University","Brigham Young University-Idaho",
  "New Mexico State University","Eastern New Mexico University",
  "New Mexico Highlands University","Western New Mexico University",
  "New Mexico Institute of Mining and Technology",
  // Southwest
  "University of Arizona","Arizona State University","Northern Arizona University",
  "Embry-Riddle Aeronautical University","Grand Canyon University",
  "University of Nevada Las Vegas","University of Nevada Reno",
  "Nevada State University","Sierra Nevada University",
  // Religious & Faith-Based
  "Liberty University","Regent University","Oral Roberts University",
  "Lee University","Bryan College","John Brown University",
  "Abilene Christian University","Hardin-Simmons University","Lubbock Christian University",
  "Dallas Baptist University","Houston Baptist University","LeTourneau University",
  "Southwestern Assemblies of God University","Texas Wesleyan University",
  "Biola University","Azusa Pacific University","Fresno Pacific University",
  "Point Loma Nazarene University","Westmont College","Vanguard University",
  "Hope International University","The Master's University","California Baptist University",
  "APU University","George Fox University","Northwest Christian University",
  "Oregon State University","Portland State University",
  // Art & Design
  "Rhode Island School of Design","Pratt Institute","Parsons School of Design",
  "School of Visual Arts","Maryland Institute College of Art",
  "Massachusetts College of Art and Design","Art Center College of Design",
  "Otis College of Art and Design","California College of the Arts",
  "Savannah College of Art and Design","Columbus College of Art and Design",
  "Cleveland Institute of Art","Minneapolis College of Art and Design",
  "Ringling College of Art and Design","Pacific Northwest College of Art",
  // Music
  "Berklee College of Music","Juilliard School","Eastman School of Music",
  "New England Conservatory","Peabody Conservatory","Oberlin Conservatory",
  "Cleveland Institute of Music","San Francisco Conservatory of Music",
  "Manhattan School of Music","Curtis Institute of Music",
  "Berklee Valencia Campus","Frost School of Music",
  // Business Specific
  "Babson College","Bentley University","Thunderbird School of Global Management",
  // Military
  "United States Military Academy (West Point)","United States Naval Academy",
  "United States Air Force Academy","United States Coast Guard Academy",
  "United States Merchant Marine Academy","Norwich University","The Citadel",
  "Virginia Military Institute","Texas A&M University",
  // Additional Major Schools
  "Syracuse University","Temple University","George Mason University",
  "Florida International University","University of Central Florida",
  "University of South Florida","Florida Atlantic University",
  "Florida Gulf Coast University","Florida Polytechnic University",
  "Nova Southeastern University","Florida Institute of Technology",
  "Palm Beach Atlantic University","Rollins College","Stetson University",
  "Eckerd College","Lynn University","Saint Leo University","Embry-Riddle",
  "Georgia State University","Georgia Southern University",
  "Mercer University","Kennesaw State University","Berry College",
  "Armstrong State University","Savannah State University",
  "Georgia Gwinnett College","Reinhardt University",
  "University of North Carolina Charlotte","University of North Carolina Wilmington",
  "University of North Carolina Greensboro","University of North Carolina Asheville",
  "University of North Carolina Pembroke","East Carolina University",
  "Appalachian State University","Western Carolina University",
  "Elizabeth City State University","Fayetteville State University",
  "North Carolina Central University","Winston-Salem State University",
  "Methodist University","Belmont Abbey College","Campbell University",
  "Gardner-Webb University","Queens University of Charlotte",
  "University of South Carolina Aiken","Coastal Carolina University",
  "College of Charleston","The Citadel","Winthrop University","Lander University",
  "Francis Marion University","Presbyterian College","Newberry College",
  "Furman University","Wofford College","Converse University",
  // More complete national coverage
  "Grand Valley State University","Ferris State University","Western Michigan University",
  "Eastern Michigan University","Central Michigan University","Northern Michigan University",
  "Lake Superior State University","Saginaw Valley State University",
  "Oakland University","Wayne State University","University of Michigan-Dearborn",
  "University of Michigan-Flint","Kettering University","Lawrence Technological University",
  "Andrews University","Calvin University","Hope College","Aquinas College",
  "Alma College","Albion College","Adrian College","Spring Arbor University",
  "Cornerstone University","Grand Rapids Theological Seminary",
  "Ohio University","Wright State University","Bowling Green State University",
  "Kent State University","University of Toledo","University of Akron",
  "Youngstown State University","Cleveland State University","John Carroll University",
  "Xavier University","Mount St. Joseph University","Capital University",
  "Ohio Dominican University","Otterbein University","Heidelberg University",
  "Defiance College","Wilmington College","Wittenberg University","Antioch College",
  "Malone University","Walsh University","Franciscan University of Steubenville",
  "Ursuline College","Notre Dame College","Ashland University",
];

// ============================================
// Remove duplicates from SCHOOL_NAMES_LIST
// ============================================
(function() {
  const seen = new Set();
  const filtered = [];
  SCHOOL_NAMES_LIST.forEach(n => {
    const key = n.toLowerCase().trim();
    if (!seen.has(key)) {
      seen.add(key);
      filtered.push(n);
    }
  });
  SCHOOL_NAMES_LIST.length = 0;
  filtered.forEach(n => SCHOOL_NAMES_LIST.push(n));
})();
